# Generated by Django 4.0.3 on 2022-11-03 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Com', models.CharField(max_length=100)),
                ('Rol', models.CharField(max_length=100)),
                ('Edu', models.CharField(max_length=100)),
                ('Sal', models.CharField(max_length=100)),
                ('Exp', models.CharField(max_length=100)),
                ('Las', models.CharField(max_length=100)),
                ('Loc', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('describe', models.CharField(max_length=100)),
                ('create_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
