# Generated by Django 4.0.3 on 2022-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Edu',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
