# Generated by Django 4.0.3 on 2022-11-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_job_edu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='describe',
            field=models.CharField(max_length=10000),
        ),
    ]
