# Generated by Django 4.0.3 on 2022-11-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_job_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.CharField(max_length=10000),
        ),
    ]
