# Generated by Django 4.0.3 on 2022-11-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='create_at',
            field=models.CharField(max_length=10000),
        ),
    ]
