# Generated by Django 4.0.3 on 2022-11-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_det'),
    ]

    operations = [
        migrations.AddField(
            model_name='det',
            name='area',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
