# Generated by Django 4.0.3 on 2023-02-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_det_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Det',
            new_name='feedback',
        ),
    ]
